version: '3'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081