DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

CREATE SEQUENCE IF NOT EXISTS cart_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS image_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS orders_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS payment_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS post_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS product_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS review_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS role_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS subscription_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS tag_seq start with 1 increment by 50;
CREATE SEQUENCE IF NOT EXISTS users_seq start with 1 increment by 50;

create table cart (id_cart bigint not null, id_user bigint unique, timestamp timestamp(6), primary key (id_cart));
create table cart_product (id_cart bigint not null, id_product bigint not null, quantity bigint, primary key (id_cart, id_product));
create table image (id_image bigint not null, id_post bigint, extension varchar(255), name varchar(255), primary key (id_image));
create table likes (id_post bigint not null, id_user bigint not null);
create table order_product (id_order bigint not null, id_product bigint not null, quantity bigint, primary key (id_order, id_product));
create table orders (id_order bigint not null, id_payment bigint unique, id_user bigint, timestamp timestamp(6), state varchar(255) check (state in ('NOT_PAID','PROCESSING','SHIPPED','DELIVERED','CANCELLED','RETURNED')), primary key (id_order));
create table payment (amount bigint, id_payment bigint not null, timestamp timestamp(6), primary key (id_payment));
create table post (id_post bigint not null, id_user bigint, views bigint, name varchar(255), primary key (id_post));
create table post_tag (id_post bigint not null, id_tag bigint not null);
create table product (price integer, id_post bigint unique, id_product bigint not null, description varchar(255), name varchar(255), primary key (id_product));
create table review (rating integer not null check ((rating<=5) and (rating>=1)), id bigint not null, id_post bigint, id_user bigint, description varchar(255), title varchar(255), primary key (id));
create table role (id_role bigint not null, name varchar(255), primary key (id_role));
create table roles (id_role bigint not null, id_user bigint not null);
create table subscription (id_subscriber bigint, id_subscription bigint not null, id_user bigint, timestamp timestamp(6), primary key (id_subscription));
create table tag (id_tag bigint not null, name varchar(255), primary key (id_tag));
create table users (id_user bigint not null, email varchar(255), password varchar(255), username varchar(255), primary key (id_user));

alter table if exists cart add constraint FKk0lcwd6e5q8ldue7je6efhdot foreign key (id_user) references users;
alter table if exists cart_product add constraint FKm778sxvaac8r8mi6rqgb876gm foreign key (id_cart) references cart;
alter table if exists cart_product add constraint FKr7eix56fc7n75p6kn03syh0ce foreign key (id_product) references product;
alter table if exists image add constraint FKfu33yyd0ooyym34y104rbwwi9 foreign key (id_post) references post;
alter table if exists likes add constraint FKmkwxnlcmsbelo7wj13mw6j7g6 foreign key (id_post) references users;
alter table if exists likes add constraint FKckc9gaeef63e3fh3a3smi01md foreign key (id_user) references post;
alter table if exists order_product add constraint FKg3uugag7e9dxyx74h2tftyp1c foreign key (id_order) references orders;
alter table if exists order_product add constraint FKkm8jfm4t1ocixswclleb7xkxj foreign key (id_product) references product;
alter table if exists orders add constraint FK5phng0rr9yex7v321tef65svq foreign key (id_payment) references payment;
alter table if exists orders add constraint FKtb6jdc061vu6ydv1445lrigtb foreign key (id_user) references users;
alter table if exists post add constraint FK3n2i1j8bfx7d7ac00iohhimul foreign key (id_user) references users;
alter table if exists post_tag add constraint FK6kxt94egt0xu0tiacm9u5lbpq foreign key (id_post) references tag;
alter table if exists post_tag add constraint FKm45wvu8sdiw4ajdejywi6nrvv foreign key (id_tag) references post;
alter table if exists product add constraint FK4tqnib1gw6uakmn8fbhyg7u9x foreign key (id_post) references post;
alter table if exists review add constraint FK1kahqq7u7xs4mx4snpqmpyjhf foreign key (id_user) references users;
alter table if exists review add constraint FKr8bl551uccq5eyqpby6av2bm9 foreign key (id_post) references post;
alter table if exists roles add constraint FK7wv9yr558l79cf0pw7mwu3prc foreign key (id_role) references role;
alter table if exists roles add constraint FKi82msnobu0w6tf9u0s4kan6d foreign key (id_user) references users;
alter table if exists subscription add constraint FK2jbbyv8p9j8q0ih6gccx3oe9n foreign key (id_subscriber) references users;
alter table if exists subscription add constraint FK62h2bb9uvmjcjoada9y0iicx3 foreign key (id_user) references users;
